src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>Text Value</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AnswerResponse__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipLabel>Answer Responses</relationshipLabel>
        <relationshipName>AnswerResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answer Responses</relationshipLabel>
        <relationshipName>AnswerResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Response</label>
    <nameField>
        <displayFormat>AR-{00000000}</displayFormat>
        <label>Answer Reponse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Multiple Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Options</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>IsCorrect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions Responses</relationshipLabel>
        <relationshipName>QuestionsResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{00000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuestionResponseService.cls
public with sharing class QuestionResponseService {
	
	public static void setIsCorrect(List<QuestionResponse__c> records) {
		Set<Id> questionResponseIds =
			new Map<Id,QuestionResponse__c>(records).keySet();
		List<QuestionResponse__c> questionResponses =
			new QuestionsResponsesSelector().selectByIdWithAnswersResponses(questionResponseIds);
		Map<Id,Question__c> questionsMap = new Map<Id,Question__c>(
			new QuestionsSelector().selectByQuestionResponseIdWithCorrectAnswers(questionResponseIds));

		for (QuestionResponse__c questionResponse: questionResponses) {
			questionResponse.IsCorrect__c = true;
			if (questionsMap.containsKey(questionResponse.Question__c)) {
				if( questionsMap.get(questionResponse.Question__c).Type__c == 'Checkbox' ||
				questionsMap.get(questionResponse.Question__c).Type__c == 'Radio'){
					if (questionResponse.AnswersResponses__r.size() ==
						questionsMap.get(questionResponse.Question__c).Answers__r.size()) {
						for(AnswerResponse__c answerResponse: questionResponse.AnswersResponses__r) {
							if (!(new Map<Id,Answer__c>(
								questionsMap.get(questionResponse.Question__c).Answers__r)
									.containsKey(answerResponse.Answer__c))) {
								questionResponse.IsCorrect__c = false;
							}
						}
					} else {
						questionResponse.IsCorrect__c = false;
					}
				}
				if (questionsMap.get(questionResponse.Question__c).Type__c == 'Text') {
					if (questionsMap.get(questionResponse.Question__c).TextValue__c !=
						questionResponse.TextValue__c) {
						questionResponse.IsCorrect__c = false;
					}
				}
			} else {
				questionResponse.IsCorrect__c = false;
			}
			new Map<Id,QuestionResponse__c>(records).get(questionResponse.Id).IsCorrect__c =
				questionResponse.IsCorrect__c;
		}
	}
}