src/objects/AnswerOption__c.object
<CustomObject>
    <fields>
        <fullName>AnswerOptionText__c</fullName>
        <label>Answer Option Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsCorrect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MatchingText__c</fullName>
        <label>Matching Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>AnswerOptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <displayFormat>AO-{00000000}</displayFormat>
        <label>Answer Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Module__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>IsCorrect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions Responses</relationshipLabel>
        <relationshipName>QuestionsResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{00000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuestionsSelector.cls
public class QuestionsSelector extends SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                Question__c.Id,
                Question__c.Name,
                Question__c.FieloELR__IncorrectWeight__c,
                Question__c.FieloELR__Module__c,
                Question__c.FieloELR__Order__c,
                Question__c.FieloELR__PenaltyPerAttempt__c,
                Question__c.FieloELR__Type__c,
                Question__c.FieloELR__CorrectWeight__c
            };
    }

    public QuestionsSelector(Set<String> fields){
        super(fields);
    }

    public QuestionsSelector(){
        super();
    }

    public Schema.SObjectType getSObjectType(){
        return Question__c.sObjectType;
    }

    public List<Question__c> selectById(Set<Id> questionIds) {
        return (List<Question__c>) selectSObjectsById(questionIds);
    }

    public List<Question__c> selectByIdWithCorrectAnswers(Set<Id> questionIds) {
     List<Question__c> listQuestion;

     if(Schema.sObjectType.Question__c.isAccessible()){	

        listQuestion = (List<Question__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', (SELECT Id, Name, AnswerOptionText__c, MatchingText__c FROM AnswerOptions__r WHERE IsCorrect__c = true) ' +
                  'FROM {1} ' +
                  'WHERE Id IN :questionIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

                     }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }

    public List<Question__c> selectByIdWithQuestionResponses(Set<Id> questionIds) {
        List<Question__c> listQuestion;

     if(Schema.sObjectType.Question__c.isAccessible()){	

        listQuestion = (List<Question__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', (SELECT Id FROM QuestionsResponses__r LIMIT 1) ' +
                  'FROM {1} ' +
                  'WHERE Id IN :questionIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

            }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }

    public List<Question__c> selectByModuleHavingAnswers(Set<Id> moduleIds) {
      List<Question__c> listQuestion;

     if(Schema.sObjectType.Question__c.isAccessible()){	

        listQuestion = (List<Question__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', (SELECT Id, IsCorrect__c ' +
                  '   FROM AnswerOptions__r ' +
                  '   ORDER BY IsCorrect__c DESC ' +
                  '   LIMIT 2) ' +
                  'FROM {1} ' +
                  'WHERE Module__c IN :moduleIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

        }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }

    public List<Question__c> selectByIdHavingAnswers(Set<Id> questionIds) {
      List<Question__c> listQuestion;

     if(Schema.sObjectType.Question__c.isAccessible()){	

        listQuestion = (List<Question__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', (SELECT Id, IsCorrect__c ' +
                  '   FROM AnswerOptions__r) ' +
                  'FROM {1} ' +
                  'WHERE Id IN :questionIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

            }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }

    public List<Question__c> selectByIdWithActiveModule(Set<Id> questionIds) {
        List<Question__c> listQuestion;

     if(Schema.sObjectType.Question__c.isAccessible()){	

        listQuestion = (List<Question__c>) Database.query(String.format(
                'SELECT {0} ' +
                  'FROM {1} ' +
                  'WHERE Module__r.IsActive__c = true ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

            }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }

     public List<Question__c> selectByModule(Set<Id> moduleIds) {
      List<Question__c> listQuestion;

     if(Schema.sObjectType.Question__c.isAccessible()){	

        listQuestion = (List<Question__c>) Database.query(String.format(
                'SELECT {0} ' +
                  'FROM {1} ' +
                  'WHERE (Module__c IN :moduleIds) ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

            }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }

    public List<Question__c> selectByModuleHavingAnswerOptions(Set<Id> moduleIds, Set<String> answerOptionFields) {
      List<Question__c> listQuestion;

     if(Schema.sObjectType.Question__c.isAccessible()){	

        listQuestion = (List<Question__c>) Database.query(String.format('SELECT {0} ' +
                   ', (SELECT {1} FROM AnswerOptions__r) ' +
                  'FROM {2} ' +
                  'WHERE Module__c IN :moduleIds ' +
                  'ORDER BY {3}',
                new List<String> {
                    getFieldListString(),
                    String.join(new List<String>(answerOptionFields),','),
                    getSObjectName(),
                    getOrderBy() } ));

            }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }

    public List<AggregateResult> selectByModuleGroupByModule(Set<Id> moduleIds) {

        List<Question__c> listQuestion;

       if(Schema.sObjectType.Question__c.isAccessible()){	
        listQuestion =  [SELECT MAX(Order__c) order, Module__c FROM Question__c WHERE Module__c in : moduleIds GROUP BY Module__c];
      }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;

    }
}