src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AnswerResponse__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipLabel>Answer Responses</relationshipLabel>
        <relationshipName>AnswerResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answer Responses</relationshipLabel>
        <relationshipName>AnswerResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Response</label>
    <nameField>
        <displayFormat>AR-{00000000}</displayFormat>
        <label>Answer Reponse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>Key</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{00000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AnswerResponses.cls
public class AnswerResponses extends SObjectDomain {

	public AnswerResponses(List<AnswerResponse__c> records) {
        super(records);
    }

    public class Constructor implements SObjectDomain.IConstructable {
        public SObjectDomain construct(List<AnswerResponse__c> sObjectList) {
            return new AnswerResponses(sObjectList);
        }
    }

    public override void onBeforeInsert() {
 		setKeys((List<AnswerResponse__c>) records);
    }

    public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
    }

    private void setKeys(List<AnswerResponse__c> records) {
    	for(AnswerResponse__c answerResponse : records) {
			if(answerResponse.QuestionResponse__c != null && answerResponse.Answer__c != null) {
				answerResponse.Key__c = String.valueOf(answerResponse.QuestionResponse__c).substring(0, 15) + String.valueOf(answerResponse.Answer__c).substring(0, 15);   
    		}
    	}
    }
}