src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>AnswerOption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer Option</label>
        <referenceTo>AnswerOption__c</referenceTo>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>Text Value</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AnswerOption__c.object
<CustomObject>
    <fields>
        <fullName>IsCorrect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>AnswerOptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <displayFormat>AO-{00000000}</displayFormat>
        <label>Answer Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Module__c.object
<CustomObject>
    <fields>
        <fullName>QuestionPool__c</fullName>
        <label>Question Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ModuleResponse__c.object
<CustomObject>
    <fields>
        <fullName>IsSubmitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Module Responses</relationshipLabel>
        <relationshipName>ModuleResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NumberOfAttempt__c</fullName>
        <label>Number of Attempt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Module Response</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Module Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>IsCorrect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSubmitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ModuleResponse__c</fullName>
        <label>Module Response</label>
        <referenceTo>ModuleResponse__c</referenceTo>
        <relationshipLabel>Questions Reponses</relationshipLabel>
        <relationshipName>QuestionResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NumberOfAttempt__c</fullName>
        <label>Number of Attempt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions Responses</relationshipLabel>
        <relationshipName>QuestionsResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{00000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuestionResponsesSelector.cls
public class QuestionResponsesSelector extends SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                QuestionResponse__c.Id,
                QuestionResponse__c.Name,
                QuestionResponse__c.ModuleResponse__c,
                QuestionResponse__c.IsCorrect__c,
                QuestionResponse__c.IsSubmitted__c,
                QuestionResponse__c.NumberOfAttempt__c,
                QuestionResponse__c.TextValue__c,
                QuestionResponse__c.ExternalKey__c,
                QuestionResponse__c.Question__c
            };
    }

    public QuestionResponsesSelector(Set<String> fields){
        super(fields);
    }

    public QuestionResponsesSelector(){
        super();
    }

    public Schema.SObjectType getSObjectType(){
        return QuestionResponse__c.sObjectType;
    }

    public List<QuestionResponse__c> selectById(Set<Id> questionResponseIds){
        return (List<QuestionResponse__c>) selectSObjectsById(questionResponseIds);
    }

    public List<QuestionResponse__c> selectByIdWithAnswers(Set<Id> questionResponseIds) {
    
    List<QuestionResponse__c> listQuestion;

     if(Schema.sObjectType.QuestionResponse__c.isAccessible() && Schema.sObjectType.Answer__c.isAccessible()){	
        listQuestion = (List<QuestionResponse__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', (SELECT Id, AnswerOption__c, TextValue__c, Name FROM Answers__r) ' +
                  'FROM {1} ' +
                  'WHERE Id IN :questionResponseIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

                     }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }

    public List<QuestionResponse__c> selectByKeyAndCorrect(Set<String> keys) {
        List<QuestionResponse__c> listQuestion;

     if(Schema.sObjectType.QuestionResponse__c.isAccessible()){	

        listQuestion = (List<QuestionResponse__c>) Database.query(String.format(
                'SELECT {0} ' +
                  'FROM {1} ' +
                  'WHERE ExternalKey__c IN : keys AND IsCorrect__c = true ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

              }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }

    public List<QuestionResponse__c> selectByKeyAndSubmitted(Set<Id> questionResponseIds) {
        List<QuestionResponse__c> listQuestion;

     if(Schema.sObjectType.QuestionResponse__c.isAccessible()){	

        listQuestion = (List<QuestionResponse__c>) Database.query(String.format(
                'SELECT {0} ' +
                  'FROM {1} ' +
                  'WHERE Id IN :questionResponseIds AND IsSubmitted__c = true ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

              }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }

    public List<AggregateResult> selectByModuleResponseGroupByModuleResponse(Set<Id> moduleResponseIds) {
    
    List<AggregateResult> listQuestion;

     if(Schema.sObjectType.QuestionResponse__c.isAccessible()){	

        listQuestion = [SELECT ModuleResponse__r.Id ModuleResponse, Question__r.Id Question, 
                    MAX(ModuleResponse__r.Module__r.QuestionPool__c) QuestionPool
                FROM QuestionResponse__c 
                WHERE ModuleResponse__c in : moduleResponseIds 
                GROUP BY ModuleResponse__r.Id, Question__r.Id
                HAVING MAX(ModuleResponse__r.Module__r.QuestionPool__c) != null 
                ORDER BY ModuleResponse__r.Id, Question__r.Id];

                 }else{
            throw new FieloException(Label.CannotInsertUpdateRecords);
          }

          return listQuestion;
    }    
}