src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>AnswerOption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer Option</label>
        <referenceTo>AnswerOption__c</referenceTo>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>Text Value</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AnswerOption__c.object
<CustomObject>
    <label>Answer Option</label>
    <nameField>
        <displayFormat>AO-{00000000}</displayFormat>
        <label>Answer Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>SubscriptionMode__c</fullName>
        <inlineHelpText>Choose &quot;Manual&quot; to require members to join a course before participating, or &quot;Automatic&quot; to allow members to jump right into taking modules.</inlineHelpText>
        <label>Subscription Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Automatic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Module__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Course to which the module belongs.</description>
        <inlineHelpText>Course to which the module belongs.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Modules</relationshipLabel>
        <relationshipName>Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Multiple Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Options</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>IsCorrect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions Responses</relationshipLabel>
        <relationshipName>QuestionsResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{00000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDetermineQuestionResponseCorrection.cls
@isTest
private class TestDetermineQuestionResponseCorrection{
    private static String errorMsg;

    @testSetup static void setup(){
        MockUpFactory.InsertTestData();
    }

    /*	TEST-1814
    	Determine Question Response Correction
    	- Question from type Single Choice is correct (OK)
    */
    @isTest static void ELR_0011_FB() {
    	Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];

        course.SubscriptionMode__c = 'Automatic';

        update course;

        MockUpFactory.activateCourse();

        Module__c module = [SELECT Id FROM Module__c WHERE Name = 'Basic'];
        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];

        ModuleService.ModuleWrapper moduleWrapper = FieloELR.ModuleService.takeModule(
            module.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );

        System.assert(moduleWrapper.moduleResponse.Id != null);

        MockUpFactory.answerModuleCorrectly(moduleWrapper);

        List<QuestionResponse__c> questionResponses = [SELECT Id, IsCorrect__c FROM QuestionResponse__c WHERE Question__r.Type__c = 'Single Choice' AND Question__r.Module__c = :module.Id];

        System.assertEquals(true, questionResponses[0].IsCorrect__c);
    }

    /*	TEST-1815
    	Determine Question Response Correction
    	- Question from type Single Choice is not correct (OK)
    */
    @isTest static void ELR_0011_FA1() {
    	Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];

        course.SubscriptionMode__c = 'Automatic';

        update course;

        MockUpFactory.activateCourse();

        Module__c module = [SELECT Id FROM Module__c WHERE Name = 'Basic'];
        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];

        ModuleService.ModuleWrapper moduleWrapper = FieloELR.ModuleService.takeModule(
            module.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );

        System.assert(moduleWrapper.moduleResponse.Id != null);

        MockUpFactory.answerModuleIncorrectly(moduleWrapper);

        List<QuestionResponse__c> questionResponses = [SELECT Id, IsCorrect__c FROM QuestionResponse__c WHERE Question__r.Type__c = 'Single Choice' AND Question__r.Module__c = :module.Id];

        System.assertEquals(false, questionResponses[0].IsCorrect__c);
    }

    /*	TEST-1816
    	Determine Question Response Correction
    	- Question from type Multiple Choice is correct (OK)
    */
    @isTest static void ELR_0011_FA2() {
    	Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];

        course.SubscriptionMode__c = 'Automatic';

        update course;

        MockUpFactory.activateCourse();

        Module__c module = [SELECT Id FROM Module__c WHERE Name = 'Basic'];
        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];

        ModuleService.ModuleWrapper moduleWrapper = FieloELR.ModuleService.takeModule(
            module.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );

        System.assert(moduleWrapper.moduleResponse.Id != null);

        MockUpFactory.answerModuleCorrectly(moduleWrapper);

        List<QuestionResponse__c> questionResponses = [SELECT Id, IsCorrect__c FROM QuestionResponse__c WHERE Question__r.Type__c = 'Multiple Choice' AND Question__r.Module__c = :module.Id];

        System.assertEquals(true, questionResponses[0].IsCorrect__c);
    }

    /*	TEST-1817
    	Determine Question Response Correction
    	- Question from type Multiple Choice is not correct (OK)
    */
    @isTest static void ELR_0011_FA3() {
    	Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];

        course.SubscriptionMode__c = 'Automatic';

        update course;

        MockUpFactory.activateCourse();

        Module__c module = [SELECT Id FROM Module__c WHERE Name = 'Basic'];
        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];

        ModuleService.ModuleWrapper moduleWrapper = FieloELR.ModuleService.takeModule(
            module.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );

        System.assert(moduleWrapper.moduleResponse.Id != null);

        MockUpFactory.answerModuleIncorrectly(moduleWrapper);

        List<QuestionResponse__c> questionResponses = [SELECT Id, IsCorrect__c FROM QuestionResponse__c WHERE Question__r.Type__c = 'Multiple Choice' AND Question__r.Module__c = :module.Id];

        System.assertEquals(false, questionResponses[0].IsCorrect__c);
    }

    /*	TEST-1818
    	Determine Question Response Correction
    	- Question from type Short Answer is correct (OK)
    */
    @isTest static void ELR_0011_FA4() {
    	Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];

        course.SubscriptionMode__c = 'Automatic';

        update course;

        MockUpFactory.activateCourse();

        Module__c module = [SELECT Id FROM Module__c WHERE Name = 'Basic'];
        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];

        ModuleService.ModuleWrapper moduleWrapper = FieloELR.ModuleService.takeModule(
            module.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );

        System.assert(moduleWrapper.moduleResponse.Id != null);

        MockUpFactory.answerModuleCorrectly(moduleWrapper);

        List<QuestionResponse__c> questionResponses = [SELECT Id, IsCorrect__c FROM QuestionResponse__c WHERE Question__r.Type__c = 'Short Answer' AND Question__r.Module__c = :module.Id];

        System.assertEquals(true, questionResponses[0].IsCorrect__c);
    }

    /*	TEST-1819
    	Determine Question Response Correction
    	- Question from type Short Answer is not correct (OK)
    */
    @isTest static void ELR_0011_FA5() {
    	Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];

        course.SubscriptionMode__c = 'Automatic';

        update course;

        MockUpFactory.activateCourse();

        Module__c module = [SELECT Id FROM Module__c WHERE Name = 'Basic'];
        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];

        ModuleService.ModuleWrapper moduleWrapper = FieloELR.ModuleService.takeModule(
            module.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );

        System.assert(moduleWrapper.moduleResponse.Id != null);

        MockUpFactory.answerModuleIncorrectly(moduleWrapper);

        List<QuestionResponse__c> questionResponses = [SELECT Id, IsCorrect__c FROM QuestionResponse__c WHERE Question__r.Type__c = 'Short Answer' AND Question__r.Module__c = :module.Id];

        System.assertEquals(false, questionResponses[0].IsCorrect__c);
    }

    /*	TEST-1820
    	Determine Question Response Correction
    	- Question from type Statement is correct (OK)
    */
    @isTest static void ELR_0011_FA6() {
    	Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];

        course.SubscriptionMode__c = 'Automatic';

        update course;

        MockUpFactory.activateCourse();

        Module__c module = [SELECT Id FROM Module__c WHERE Name = 'Basic'];
        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];

        ModuleService.ModuleWrapper moduleWrapper = FieloELR.ModuleService.takeModule(
            module.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );

        System.assert(moduleWrapper.moduleResponse.Id != null);

        MockUpFactory.answerModuleCorrectly(moduleWrapper);

        List<QuestionResponse__c> questionResponses = [SELECT Id, IsCorrect__c FROM QuestionResponse__c WHERE Question__r.Type__c = 'Statement' AND Question__r.Module__c = :module.Id];

        System.assertEquals(true, questionResponses[0].IsCorrect__c);
    }

    /*	TEST-1821
    	Determine Question Response Correction
    	- Question from type Statement is not correct (OK)
    */
    @isTest static void ELR_0011_FA7() {
    	Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];

        course.SubscriptionMode__c = 'Automatic';

        update course;

        MockUpFactory.activateCourse();

        Module__c module = [SELECT Id FROM Module__c WHERE Name = 'Basic'];
        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];

        ModuleService.ModuleWrapper moduleWrapper = FieloELR.ModuleService.takeModule(
            module.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );

        System.assert(moduleWrapper.moduleResponse.Id != null);

        MockUpFactory.answerModuleIncorrectly(moduleWrapper);

        List<QuestionResponse__c> questionResponses = [SELECT Id, IsCorrect__c FROM QuestionResponse__c WHERE Question__r.Type__c = 'Statement' AND Question__r.Module__c = :module.Id];

        System.assertEquals(false, questionResponses[0].IsCorrect__c);
    }

    /*	TEST-1822
    	Determine Question Response Correction
    	- Question from type Matching Options is correct (OK)
    */
    @isTest static void ELR_0011_FA8() {
    	Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];

        course.SubscriptionMode__c = 'Automatic';

        update course;

        MockUpFactory.activateCourse();

        Module__c module = [SELECT Id FROM Module__c WHERE Name = 'Basic'];
        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];

        ModuleService.ModuleWrapper moduleWrapper = FieloELR.ModuleService.takeModule(
            module.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );

        System.assert(moduleWrapper.moduleResponse.Id != null);

        MockUpFactory.answerModuleCorrectly(moduleWrapper);

        List<QuestionResponse__c> questionResponses = [SELECT Id, IsCorrect__c, (SELECT AnswerOption__r.AnswerOptionText__c, AnswerOption__r.MatchingText__c, TextValue__c FROM Answers__r) FROM QuestionResponse__c WHERE Question__r.Type__c = 'Matching Options' AND Question__r.Module__c = :module.Id];

        System.debug(JSON.serializePretty(questionResponses));

        System.assertEquals(true, questionResponses[0].IsCorrect__c);
    }

    /*	TEST-1823
    	Determine Question Response Correction
    	- Question from type Matching Options is not correct (OK)
    */
    @isTest static void ELR_0011_FA9() {
    	Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];

        course.SubscriptionMode__c = 'Automatic';

        update course;

        MockUpFactory.activateCourse();

        Module__c module = [SELECT Id FROM Module__c WHERE Name = 'Basic'];
        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];

        ModuleService.ModuleWrapper moduleWrapper = FieloELR.ModuleService.takeModule(
            module.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );

        System.assert(moduleWrapper.moduleResponse.Id != null);

        MockUpFactory.answerModuleIncorrectly(moduleWrapper);

        List<QuestionResponse__c> questionResponses = [SELECT Id, IsCorrect__c FROM QuestionResponse__c WHERE Question__r.Type__c = 'Matching Options' AND Question__r.Module__c = :module.Id];

        System.assertEquals(false, questionResponses[0].IsCorrect__c);
    }
}