src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AnswerResponse__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipLabel>Answer Responses</relationshipLabel>
        <relationshipName>AnswerResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answer Responses</relationshipLabel>
        <relationshipName>AnswerResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Response</label>
    <nameField>
        <displayFormat>AR-{00000000}</displayFormat>
        <label>Answer Reponse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionResponse__c.object
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{00000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AnswersResponsesSelector.cls
public with sharing class AnswersResponsesSelector extends SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                AnswerResponse__c.Id,
                AnswerResponse__c.Name,
                AnswerResponse__c.Answer__c,
                AnswerResponse__c.QuestionResponse__c

            };
    }

    public AnswersResponsesSelector(Set<String> fields){
        super(fields);
    }

    public AnswersResponsesSelector(){
        super();
    }

    public Schema.SObjectType getSObjectType(){
        return AnswerResponse__c.sObjectType;
    }

    public List<AnswerResponse__c> selectById(Set<Id> answerResponseIds) {
        return (List<AnswerResponse__c>) selectSObjectsById(answerResponseIds);
    }
}