src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>Text Value</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AnswerResponse__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipLabel>Answer Responses</relationshipLabel>
        <relationshipName>AnswerResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answer Responses</relationshipLabel>
        <relationshipName>AnswerResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Response</label>
    <nameField>
        <displayFormat>AR-{00000000}</displayFormat>
        <label>Answer Reponse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>CorrectWeight__c</fullName>
        <label>Correct Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IncorrectWeight__c</fullName>
        <label>Incorrect Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PenaltyPerAttempt__c</fullName>
        <label>Penalty per Attempt %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Multiple Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matching Options</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>IsCorrect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSubmitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PartialGradeValue__c</fullName>
        <label>Partial Grade Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions Responses</relationshipLabel>
        <relationshipName>QuestionsResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{00000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuestionResponses.cls
public class QuestionResponses extends SObjectDomain {
	public static Set<Id> processedIds = new Set<Id>();
    public static Boolean validateAdminFields = true;

	public QuestionResponses(List<QuestionResponse__c> records) {
        super(records);
    }

    public class Constructor implements SObjectDomain.IConstructable {
        public SObjectDomain construct(List<QuestionResponse__c> sObjectList) {
            return new QuestionResponses(sObjectList);
        }
    }

    public override void onBeforeUpdate(Map<Id,SObject> existingRecords) {
        List<QuestionResponse__c> submittedRecords = new List<QuestionResponse__c>();

        for(QuestionResponse__c questionResp: (List<QuestionResponse__c>)records){
            //Add only submitted records.
            if( questionResp.IsSubmitted__c ){
            	if( !((QuestionResponse__c)existingRecords.get(questionResp.Id)).IsSubmitted__c ||
                    ((QuestionResponse__c)existingRecords.get(questionResp.Id)).IsSubmitted__c == null){
	                submittedRecords.add(questionResp);
            	}
            }
        }

        if(!submittedRecords.isEmpty()){
            setIsCorrect(submittedRecords);
        }
    }

    public static void setIsCorrect(List<QuestionResponse__c> records) {
        Set<Id> questionResponseIds = new Map<Id,QuestionResponse__c>(records).keySet();
        Set<Id> questionIds = new Set<Id>();
        for (QuestionResponse__c questionResponse:records) {
            questionIds.add(questionResponse.Question__c);
        }
        Map<Id,QuestionResponse__c> existingQuestionResponses = new Map<Id,QuestionResponse__c>(new QuestionResponsesSelector().selectByIdWithAnswersResponses(questionResponseIds));
        Map<Id,Question__c> questionsMap = new Map<Id,Question__c>(new QuestionsSelector().selectByIdWithCorrectAnswers(questionIds));

        Double incorrectWeight;
        Double questionWeight;
        Double penaltyPerQuestion;
        Integer isCorrectInt;
        Integer questionRespAttempts;

        for (QuestionResponse__c questionResponse: records) {
            questionResponse.IsCorrect__c = true;
            if (questionsMap.containsKey(questionResponse.Question__c)) {
                if( questionsMap.get(questionResponse.Question__c).Type__c == 'Multiple Choice' ||
                questionsMap.get(questionResponse.Question__c).Type__c == 'Single Choice'){
                    if (existingQuestionResponses.get(questionResponse.Id).AnswerResponses__r.size() ==
                        questionsMap.get(questionResponse.Question__c).Answers__r.size()) {
                        for(AnswerResponse__c answerResponse: existingQuestionResponses.get(questionResponse.Id).AnswerResponses__r) {
                            if (!(new Map<Id,Answer__c>(
                                questionsMap.get(questionResponse.Question__c).Answers__r)
                                    .containsKey(answerResponse.Answer__c))) {
                                questionResponse.IsCorrect__c = false;
                            }
                        }
                    } else {
                        questionResponse.IsCorrect__c = false;
                    }
                }
                if (questionsMap.get(questionResponse.Question__c).Type__c == 'Short Answer') {
                    questionResponse.IsCorrect__c = false;
                    for (Answer__c answer: questionsMap.get(questionResponse.Question__c).Answers__r) {
                        if (answer.AnswerText__c == questionResponse.TextValue__c) {
                            questionResponse.IsCorrect__c = true;
                            break;
                        }
                    }
                }
            } else {
                questionResponse.IsCorrect__c = false;
            }

            incorrectWeight = questionsMap.get(questionResponse.Question__c).IncorrectWeight__c;
            questionWeight = questionsMap.get(questionResponse.Question__c).CorrectWeight__c;
            penaltyPerQuestion = questionsMap.get(questionResponse.Question__c).PenaltyPerAttempt__c;
            isCorrectInt = questionResponse.IsCorrect__c ? 1 : 0;
            questionRespAttempts = Integer.valueOf(questionResponse.NumberOfAttempts__c);

            questionResponse.PartialGradeValue__c =
                penaltyPerQuestion != null ?
                    isCorrectInt * (questionWeight * Math.pow((1 - penaltyPerQuestion / 100),questionRespAttempts-1)) :
                    (isCorrectInt * questionWeight + (isCorrectInt - 1) * incorrectWeight);
        }
    }
}