src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>AnswerOption__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer Option</label>
        <referenceTo>AnswerOption__c</referenceTo>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionResponse__c</fullName>
        <label>Question Response</label>
        <referenceTo>QuestionResponse__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/AnswerOption__c.object
<CustomObject>
    <label>Answer Option</label>
    <nameField>
        <displayFormat>AO-{00000000}</displayFormat>
        <label>Answer Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionResponse__c.object
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{00000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AnswersSelector.cls
public class AnswersSelector extends SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                Answer__c.Id,
                Answer__c.Name,
                Answer__c.AnswerOption__c,
                Answer__c.QuestionResponse__c

          };
    }
    public AnswersSelector(Set<String> fields){
        super(fields);
    }

    public AnswersSelector(){
        super();
    }

    public Schema.SObjectType getSObjectType(){
        return Answer__c.sObjectType;
    }//test github

    public List<Answer__c> selectById(Set<Id> answerIds) {
        return (List<Answer__c>) selectSObjectsById(answerIds);
    }
}