src/objects/AnswerOption__c.object
<CustomObject>
    <fields>
        <fullName>AnswerOptionText__c</fullName>
        <label>Answer Option Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsCorrect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MatchingText__c</fullName>
        <label>Matching Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>AnswerOptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <displayFormat>AO-{00000000}</displayFormat>
        <label>Answer Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FormQuestionController.cls
public with sharing class FormQuestionController {
  /*****  Datos  *****/
    public String csObjectName{get;set;}
    public String cFilter{get;set;}
    public String cLayout{get;set;}
    public static Boolean cRecordRedirect{get;set;}
    public SObject cRecord {get;set;}  
    private Boolean queryRecordNotDone = true;

    public String fields {get{
      if ( fields == null ) {
      fields = 'Id';
          for ( Section s :sections ) {
              for ( List<FormField> r :s.rows ) {
                for ( FormField f :r ) {
                    if ( !String.isBlank(f.Name) ) {
                      fields += ', '  + f.Name;
                    }
                }
              }
          }
        }
    return fields;
    }set;}
  
  public SObject recordObject{get{
    if (queryRecordNotDone ) {
      queryRecordNotDone = false;
          if ( cRecord !=null && cRecord.Id != null ) {
                fields = String.escapeSingleQuotes(fields);
                csObjectName = String.escapeSingleQuotes(csObjectName);

              Id recordId = cRecord.Id;
              String query = 'SELECT  ' + fields;
              query += ' FROM ' + csObjectName;
              query += ' WHERE Id = : recordId ';
              
                if( Schema.getGlobalDescribe().get(csObjectName).isAccessible() ){
					recordObject = Database.query(query)[0];
				}
          } else {
              recordObject = Schema.getGlobalDescribe().get(csObjectName).newSObject() ;
          }
        }
        return recordObject;
    }set;}

  /*****  Secciones Y Fields  *****/
    public String cFieldset{get;set;}

    public class Section {
        public String Name{get;set;}
        public List<List<FormField>> Rows{get;set;}
        public String CssClass{get;set;}
    }

    public class FormField {
        public String Type{get;set;}
        public String MetaField{get;set;}
        public String Name{get;set;}
        public String onchange{get;set;}
        public String Label{get;set;}
        public String Value{get;set;}
        public String WhereCondition{get;set;}
        public Boolean Required{get;set;}

        public String getRequiredValue () {
            if ( Required != null ) {
                return Required ? 'true' : 'false';
            }
            return '';
        }
    }

    public List<Section> sections { get {
        if ( sections == null ) {
            if ( !String.isBlank(cFieldset)  ) {
                // Si empieza con [ es un valor seteado en una visual force => lo tiene que modificar para que sea json
                if ( !cFieldset.startsWith('[') ) {
                    cFieldset = '[' + cFieldset.replace('\'', '"') + ']';
                }
                try {
                    if ( cLayout == 'inline'  ) {
                        Section s = new Section();
                        s.Name = '';
                        s.Rows =  new List<List<FormField>>();
                        s.Rows.add( (List<FormField>) JSON.deserialize( cFieldset, List<FormField>.class ));
                        sections = new List<Section>();
                        sections.add(s);
                    } else {
                        sections = (List<Section>) JSON.deserialize( cFieldset, List<Section>.class );
                    }
                } catch( JSONException e ) {
                    system.debug(LoggingLevel.ERROR, 'INVALID JSON ' + cFieldset );        
                }
            } else {
                sections = new List<Section>();
            }
        }
        return sections;
        } set;
    }

  /*****  Piclklist Values *****/
    private Map<String, Schema.SObjectField> fieldMap { get {
      if ( fieldMap == null && csObjectName != null ) {
          Schema.DescribeSObjectResult[] describes = Schema.describeSObjects(new String[]{ csObjectName });
          fieldMap = describes.get(0).fields.getMap();
      }
      return fieldMap;
    } set; }

    public Map<String, String> mapOptionsString { get {
      if ( mapOptionsString == null && mapPicklistOptions != null ) {
          mapOptionsString = new Map<String, String>();
          for ( String key : mapPicklistOptions.keySet() ) {
            String options = '';
            for ( PicklistController.Entry p : mapPicklistOptions.get(key) ) {
                options += ',{ "id": "' + p.Id + '", "label": "' + p.Label + '" }';
            }
            if ( options != '') {
                mapOptionsString.put(key,'[' + options.substring(1) + ']');
            } else {
                mapOptionsString.put(key,'[]');
            }
          }
      }
      return mapOptionsString;
    } set;}

    public Map<String, List<PicklistController.Entry>> mapPicklistOptions { get {
      if ( mapPicklistOptions == null && !String.isBlank(csObjectName) ) {
          mapPicklistOptions = new Map<String, List<PicklistController.Entry>>();
          for ( Section s :sections ) {
            for ( List<FormField> ff :s.Rows ) {
                for ( FormField f :ff ) {
                  if ( (f.Type == 'picklist' ||  f.Type == 'radio'|| f.Type == 'multiselect'|| f.Type == 'checkboxes') && fieldMap.containsKey(f.Name) ) {
                      List<PicklistController.Entry> options = new List<PicklistController.Entry>();
                      Schema.DescribeFieldResult describe = fieldMap.get(f.Name).getDescribe();
                      if ( describe.getType().name() == 'PICKLIST' || describe.getType().name() == 'MULTIPICKLIST' ) {
                        List<Schema.PicklistEntry> pickListValues = describe.getPickListValues();
                        for (Schema.PicklistEntry a : pickListValues) {
                            options.add( new PicklistController.Entry(a.getValue(), a.getLabel() ));
                        }
                      } else if ( describe.getType().name() == 'REFERENCE' ) {
                        String query = 'SELECT ID, Name FROM ' + describe.getReferenceTo().get(0);
                        if ( ! String.isBlank( f.WhereCondition )  ){
                            query += ' WHERE ' + f.WhereCondition.replace('/', '\'') ;
                        }
                        query += ' LIMIT 500';

                     SObjectType convertType = describe.getReferenceTo().get(0);

                    SecurityUtils.checkObjectIsReadable(convertType);

                        for ( SObject o : Database.query(query) ) {
                            // Substring para que matche con el multipicklist (para multisegment)
                            options.add( new PicklistController.Entry( ((String)o.id).substring(0, 15),  (String)o.get('Name') ));
                        }
                      }
                      mapPicklistOptions.put( f.Name , options);
                  }
                }
            }
          }
      }
      return mapPicklistOptions;
    } set;}

    public FieloPLT__PageSettings__c getPageSettings(String pageSetingsName) {
        Set<String> fields = new Set<String>();
        for(String s : new List<String>(Schema.describeSObjects(new String[]{'FieloPLT__PageSettings__c'})[0].fields.getMap().keySet())){
            if( Schema.sObjectType.FieloPLT__PageSettings__c.fields.getMap().get(s).getDescribe().isAccessible() ){
                fields.add(s);
            }
        }

        String query = 'SELECT ';
        query += String.join(fields, ',');
        query += ' FROM FieloPLT__PageSettings__c';
        query += ' WHERE Name = :pageSetingsName' ;
        query += ' LIMIT 1';
        
        List<sObject> result;

        if(Schema.sObjectType.FieloPLT__PageSettings__c.isAccessible()){
            result = Database.query(query);
        }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

        return (FieloPLT__PageSettings__c) result.get(0);
    }

    public FieloPLT__PageSettings__c answerOptionsPS {get{
        return getPageSettings('Question (Question Wizard) > Related > Answer Option');
    }set;}

  /*****  Metodos Remote para Save y Retrieve *****/
    @RemoteAction
    public static RemoteActionResult save( FieloELR__Question__c question, List<String> questionNullFields, List<FieloELR__AnswerOption__c> answerOptions, Map<Id,List<String>> answerOptionsNullFields, List<Id> deletedIds){
      Savepoint sp;
      RemoteActionResult result = new RemoteActionResult();
        SObjectUnitOfWork uow = new SObjectUnitOfWork(new List<Schema.SobjectType>{FieloELR__Question__c.SObjectType, FieloELR__AnswerOption__c.SObjectType});
        SObjectUnitOfWork uowUpdateAO = new SObjectUnitOfWork(new List<Schema.SobjectType>{FieloELR__AnswerOption__c.SObjectType});
        System.debug(question);
      try{
            sp = Database.setSavepoint();
            for( String f :questionNullFields ) {
                if( Schema.sObjectType.Question__c.fields.get(f).getDescribe().isUpdateable() ){
                    question.put(f, null );
                }
            }

            if (question.Id == null) {
                uow.registerNew(question);
            } else {
                uow.registerDirty(question);
            }

            for( FieloELR__AnswerOption__c answerOption: answerOptions) {
                if(answerOptionsNullFields.containsKey(answerOption.Id)){
                    for(String f: answerOptionsNullFields.get(answerOption.Id)){
                        if( Schema.sObjectType.FieloELR__AnswerOption__c.fields.get(f).getDescribe().isUpdateable() ){
                            answerOption.put(f, null);
                        }
                    }
                }
                if(answerOption.Id == null){
                    uow.registerNew(answerOption, AnswerOption__c.Question__c, question);
                }else{
                    uowUpdateAO.registerDirty(answerOption);
                }
            }

            if (!deletedIds.isEmpty()) {
              uow.registerDeleted(new AnswerOptionsSelector().selectById(new Set<Id>(deletedIds)));
            }

            //done update in different uow to do the update before the insert of AOs to avoid validation rules.
             if(Schema.sObjectType.FieloELR__AnswerOption__c.isUpdateable()){
                        uowUpdateAO.commitWork();
                    }else{
                        throw new FieloException(Label.CannotInsertUpdateRecords);
                    }

                    if( Schema.sObjectType.FieloELR__Question__c.isCreateable() && Schema.sObjectType.FieloELR__Question__c.isUpdateable() && Schema.sObjectType.FieloELR__AnswerOption__c.isDeletable() ){
                        uow.commitWork();
                    }else{
                        throw new FieloException(Label.CannotInsertRecords);
                    }

          //TODO Crear Label DataSavedSuccessfully
          result.addMessage(new RemoteActionResult.RemoteActionMessage( ApexPages.Severity.Confirm, Label.DataSavedSuccessfully) );

      } catch(DmlException e) {
      // Agrega las Validation Rules asociadas al Campo
          Database.rollback(sp);
          if(ApexPages.hasMessages()){
              result.redirectURL = '';
              for(ApexPages.Message m : ApexPages.getMessages()){
                  result.addMessage(new RemoteActionResult.RemoteActionMessage(m, '' ));
              }
          } else {
            result.addMessage(new RemoteActionResult.RemoteActionMessage(e));  
          }
      }catch(Exception e){
          if(sp != null){
              Database.rollback(sp);
          }
          result.addMessage(new RemoteActionResult.RemoteActionMessage(e));
      }
      return result;
   }

    @RemoteAction
    public static sObject retrieve( String objectName, String recordId, String fields ){
        Map<String, Schema.SObjectField> fieldsMap = Schema.getGlobalDescribe().get( objectName ).getDescribe().fields.getMap();
		Set<String> newFields = new Set<String>();
		for(String s : String.split(',')){
			if( fieldsMap.get(s).getDescribe().isAccessible() ){
				newFields.add( String.escapeSingleQuotes(s) );
			}
		}

      String query = 'SELECT ' + String.join(newFields, ',');
        objectName = String.escapeSingleQuotes(objectName);
      if (objectName == 'FieloELR__Question__c') {
        query += ' ,(Select Id, FieloELR__IsCorrect__c, FieloELR__AnswerOptionText__c, FieloELR__MatchingText__c, FieloELR__Order__c From AnswerOptions__r ORDER BY FieloELR__Order__c, LastModifiedDate)';
      }

      query += ' FROM ' + objectName;
      query += ' WHERE ID = :recordId';
      query += ' LIMIT 1';
      List<sObject> result;
      
       if( Schema.getGlobalDescribe().get(objectName).getDescribe().isAccessible()){
          if( String.escapeSingleQuotes(objectName) == 'FieloELR__Question__c' && !Schema.sObjectType.AnswerOptions__c.isAccessible() || !Schema.sObjectType.AnswerOptions__c.fields.IsCorrect__c.isAccessible() || !Schema.sObjectType.AnswerOptions__c.fields.AnswerOptionText__c.isAccessible() || !Schema.sObjectType.AnswerOptions__c.fields.MatchingText__c.isAccessible() || !Schema.sObjectType.AnswerOptions__c.fields.Order__c.isAccessible()){
              throw new FieloException(Label.CannotInsertRecords);
          } 
            result = Database.query(query);
       
       }

      if ( result.size() > 0 ) {
          return result.get(0);
      }
      return null;
    }
}