src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseStatus__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses Status</relationshipLabel>
        <relationshipName>CoursesStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Course Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Tracker__c.object
<CustomObject>
    <description>Internal object. It is generated as a result of processing a Challenge Action.</description>
    <fields>
        <fullName>CourseStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Status</label>
        <referenceTo>CourseStatus__c</referenceTo>
        <relationshipLabel>Trackers</relationshipLabel>
        <relationshipName>Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, Tracker is processed. Depending on the other Challenge settings and status, several related processes may be triggered.</description>
        <inlineHelpText>If ticked, Tracker is processed.</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsReverted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, Tracker is reverted thus Points are returned to the Member.</description>
        <inlineHelpText>If ticked, Tracker is reverted thus Points are returned to the Member.</inlineHelpText>
        <label>Reverted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>FieloPLT__Transaction__c</referenceTo>
        <relationshipLabel>Trackers</relationshipLabel>
        <relationshipName>Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tracker</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Transaction__c.object
<CustomObject>
    <description>Actions that grant Points, Badges or Rewards to Members in exchange of performing specific activities.</description>
    <fields>
        <fullName>CourseStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Status</label>
        <referenceTo>CourseStatus__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, Transactions were processed by the Rule Engine.</description>
        <inlineHelpText>When ticked, Transactions were processed.</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsReverted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, Transactions were reverted by the Rule Engine.</description>
        <inlineHelpText>When ticked, Transactions were reverted.</inlineHelpText>
        <label>Reverted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Points__c</fullName>
        <description>Transaction Points.</description>
        <inlineHelpText>Enter the number of Transaction Points.</inlineHelpText>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__RevertedTransaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It shows a Transaction that was reverted.</description>
        <inlineHelpText>Transaction that was reverted.</inlineHelpText>
        <label>Reverted Transaction</label>
        <referenceTo>FieloPLT__Transaction__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Module__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Course to which the module belongs.</description>
        <inlineHelpText>Course to which the module belongs.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Modules</relationshipLabel>
        <relationshipName>Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseCardContainerController.cls
public class CourseCardContainerController {
    @AuraEnabled
    public static String getCourseRecord(String recordId, String fields) {
        try{
            Set<String> fieldNames = new Set<String>();
            Map<String,Schema.SObjectField> singleCourseDetailAccessable = Schema.SObjectType.Course__c.fields.getMap();
            for (String singleCourseDetailfieldToCheck : fields.split(',')) { 
                if (singleCourseDetailAccessable.get(singleCourseDetailfieldToCheck).getDescribe().isAccessible() ) {
                    fieldNames.add(singleCourseDetailfieldToCheck);
                } else {
                    throw new FieloException(String.format(Label.security_error_field_not_readable, new List<String>{'Course__c', singleCourseDetailfieldToCheck}));
                }
            }

            
            Set<String> queryableFields = new Set<String>();
            
            for(String fieldName:fieldNames) {
                if (fieldName == 'FieloELR__Modules__r') {
                    queryableFields.add('(SELECT Id, Name, FieloELR__Order__c FROM FieloELR__Modules__r WHERE FieloELR__IsActive__c = true) FieloELR__Modules__r');
                } else {
                    queryableFields.add(fieldName);
                }
            }
            CoursesSelector selector = new CoursesSelector(queryableFields);
            String results;

            if ( Schema.sObjectType.Course__c.isAccessible() && Schema.sObjectType.Module__c.isAccessible()) {
                if(Schema.sObjectType.Module__c.fields.Name.isAccessible() && Schema.sObjectType.Module__c.fields.FieloELR__Order__c.isAccessible() && Schema.sObjectType.Module__c.fields.FieloELR__IsActive__c.isAccessible()) {
                    results = JSON.serialize(selector.selectByIdCustom(new Set<Id>{recordId})[0]);
                } else {
                    throw new FieloException(String.format(Label.security_error_field_not_readable, new List<String>{'Module__c', 'Name,Order__c,IsActive__c'}));
                }
            } else {
                throw new FieloException(String.format(Label.security_error_object_not_readable, new List<String>{'Course__c,Module__c'}));
            }

            return results;
        } catch(DMLException e) {
            throw new AuraHandledException(e.getDMLMessage(0));
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String getConfig(String courseId, String memberId, String csFields) {
        try{
            Map<String,String> lcConfig = new Map<String,String>();
            String baseURL = Network.getLoginUrl(Network.getNetworkId());
            String uselessString = baseURL.substring(baseURL.lastIndexOf('/')+1);
            baseURL = baseURL.replace(uselessString, '');
            
            Set<String> queryableFields = new Set<String>();
            Set<String> fieldNames = new Set<String>();
            if (csFields != null) {
                Map<String,Schema.SObjectField> singleCourseStatusDetailAccessable = Schema.SObjectType.CourseStatus__c.fields.getMap();
                for (String singleCourseStatusDetailfieldToCheck : csFields.split(',')) { 
                    if (singleCourseStatusDetailAccessable.get(singleCourseStatusDetailfieldToCheck).getDescribe().isAccessible() ) {
                        fieldNames.add(singleCourseStatusDetailfieldToCheck);
                    } else {
                        throw new FieloException(String.format(Label.security_error_field_not_readable, new List<String>{'CourseStatus__c', singleCourseStatusDetailfieldToCheck}));
                    }
                }

                for(String fieldName:fieldNames) {
                    if (fieldName == 'FieloELR__Transactions__r') {
                        if (Schema.sObjectType.FieloPLT__Transaction__c.isAccessible()) {
                            if ( Schema.sObjectType.FieloPLT__Transaction__c.fields.FieloPLT__Points__c.isAccessible() && Schema.sObjectType.FieloPLT__Transaction__c.fields.FieloPLT__IsReverted__c.isAccessible() && Schema.sObjectType.FieloPLT__Transaction__c.fields.FieloPLT__IsProcessed__c.isAccessible()) {
                                queryableFields.add('(SELECT Id, FieloPLT__Points__c FROM FieloELR__Transactions__r WHERE FieloPLT__IsReverted__c = false AND FieloPLT__IsProcessed__c = true) FieloELR__Transactions__r');
                            } else {
                                throw new FieloException(String.format(Label.security_error_field_not_readable, new List<String>{'FieloPLT__Transaction__c', 'FieloPLT__Points__c,FieloPLT__IsReverted__c,FieloPLT__IsProcessed__c'}));
                            }
                        } else {
                            throw new FieloException(String.format(Label.security_error_object_not_readable, new List<String>{'FieloPLT__Transaction__c'}));
                        }
                    } else if (fieldName == 'FieloELR__Trackers__r') {
                        if (Schema.sObjectType.FieloPLT__Tracker__c.isAccessible() && Schema.sObjectType.FieloPLT__Transaction__c.isAccessible()) {
                            if (Schema.sObjectType.FieloPLT__Tracker__c.fields.FieloPLT__IsReverted__c.isAccessible() && Schema.sObjectType.FieloPLT__Tracker__c.fields.FieloPLT__IsProcessed__c.isAccessible() && Schema.sObjectType.FieloPLT__Tracker__c.fields.FieloPLT__Transaction__c.isAccessible() && Schema.sObjectType.FieloPLT__Transaction__c.fields.FieloPLT__Points__c.isAccessible()) {
                                queryableFields.add('(SELECT Id, FieloPLT__Transaction__r.FieloPLT__Points__c FROM FieloELR__Trackers__r WHERE FieloPLT__IsReverted__c = false AND FieloPLT__IsProcessed__c = true) FieloELR__Trackers__r');
                            } else {
                                throw new FieloException(String.format(Label.security_error_field_not_readable, new List<String>{'FieloPLT__Tracker__c', 'FieloPLT__Transaction__r.FieloPLT__Points__c,FieloPLT__IsReverted__c,FieloPLT__IsProcessed__c'}));
                            }
                        } else {
                            throw new FieloException(String.format(Label.security_error_object_not_readable, new List<String>{'FieloPLT__Tracker__c,FieloPLT__Transaction__c'}));
                        }
                    }
                }
            }

            List<CourseStatus__c> csList = new List<CourseStatus__c>(new CourseStatusSelector(queryableFields).selectByKey(new Set<String>{String.valueOf(courseId) + String.valueOf(memberId)}));
            
            lcConfig.put('orgId', UserInfo.getOrganizationId());
            lcConfig.put('locale', UserInfo.getLocale());
            lcConfig.put('profileId', UserInfo.getProfileId());
            lcConfig.put('communityURL', baseURL);
            lcConfig.put('joinedCourse', String.valueOf(!csList.isEmpty()));
            if (!csList.isEmpty()) {
                lcConfig.put('courseStatus', JSON.serialize(csList[0]));
            }
            return JSON.serialize(lcConfig);
        } catch(DMLException e) {
            throw new AuraHandledException(e.getDMLMessage(0));
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}