src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseStatus__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses Status</relationshipLabel>
        <relationshipName>CoursesStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Course Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Module__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Course to which the module belongs.</description>
        <inlineHelpText>Course to which the module belongs.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Modules</relationshipLabel>
        <relationshipName>Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionPool__c</fullName>
        <label>Question Pool</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ModuleResponse__c.object
<CustomObject>
    <fields>
        <fullName>CourseStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Status</label>
        <referenceTo>CourseStatus__c</referenceTo>
        <relationshipLabel>Modules Responses</relationshipLabel>
        <relationshipName>ModuleResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GradePercent__c</fullName>
        <label>Grade %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>GradeValue__c</fullName>
        <label>Grade Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSubmitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Module Responses</relationshipLabel>
        <relationshipName>ModuleResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NumberOfAttempt__c</fullName>
        <label>Number of Attempt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Module Response</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Module Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionResponse__c.object
<CustomObject>
    <fields>
        <fullName>IsCorrect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSubmitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ModuleResponse__c</fullName>
        <label>Module Response</label>
        <referenceTo>ModuleResponse__c</referenceTo>
        <relationshipLabel>Questions Reponses</relationshipLabel>
        <relationshipName>QuestionResponses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NumberOfAttempt__c</fullName>
        <label>Number of Attempt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PartialGradeValue__c</fullName>
        <label>Partial Grade Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions Responses</relationshipLabel>
        <relationshipName>QuestionsResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{00000000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ModuleResponsesSelector.cls
public class ModuleResponsesSelector extends SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                ModuleResponse__c.Id,
                ModuleResponse__c.Name,
                ModuleResponse__c.Date__c,
                ModuleResponse__c.GradePercent__c,
                ModuleResponse__c.GradeValue__c,
                ModuleResponse__c.IsApproved__c,
                ModuleResponse__c.IsSubmitted__c,
                ModuleResponse__c.Module__c,
                ModuleResponse__c.NumberOfAttempt__c
            };
    }

    public ModuleResponsesSelector(Set<String> fields){
        super(fields);
    }

    public ModuleResponsesSelector(){
        super();
    }

    public Schema.SObjectType getSObjectType(){
        return ModuleResponse__c.sObjectType;
    }

    public List<ModuleResponse__c> selectById(Set<Id> moduleResponseIds){
        return (List<ModuleResponse__c>) selectSObjectsById(moduleResponseIds);
    }

    public List<ModuleResponse__c> selectByIdAndSubmitted(Set<Id> recordIds) {


        List<ModuleResponse__c> listModuleResponse;

     if(Schema.sObjectType.ModuleResponse__c.isAccessible()){	

        listModuleResponse = (List<ModuleResponse__c>) Database.query(String.format(
                'SELECT {0} ' +
                  'FROM {1} ' +
                  'WHERE Id IN : recordIds AND IsSubmitted__c = true ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

         }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listModuleResponse;
    }

    public List<ModuleResponse__c> selectByIdWithQuestionResponses(Set<Id> moduleResponseIds) {
        List<ModuleResponse__c> listModuleResponse;

     if(Schema.sObjectType.ModuleResponse__c.isAccessible()){	

        listModuleResponse = (List<ModuleResponse__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', (SELECT Id, ' +
                    'IsCorrect__c, ' +
                    'IsSubmitted__c, ' +
                    'ModuleResponse__c, ' +
                    'NumberOfAttempt__c, ' +
                    'Question__c, ' +
                    'PartialGradeValue__c, ' +
                    'TextValue__c, ' +
                    'ExternalKey__c, ' +
                    'Name FROM QuestionResponses__r) ' +
                  'FROM {1} ' +
                  'WHERE Id IN :moduleResponseIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

                     }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listModuleResponse;
    }

    public List<ModuleResponse__c> selectByKeyAndApproved(Set<String> keys) {
        List<ModuleResponse__c> listModuleResponse;

     if(Schema.sObjectType.ModuleResponse__c.isAccessible()){	

        listModuleResponse = (List<ModuleResponse__c>) Database.query(String.format(
                'SELECT {0} ' +
                  'FROM {1} ' +
                  'WHERE ExternalKey__c IN : keys AND IsApproved__c = true ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

                    }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listModuleResponse;
    }

    public List<ModuleResponse__c> selectByKeyAndApproved(Set<String> keys, Set<Id> moduleExcludeIds) {
        String query = 'SELECT {0} ' +
                  'FROM {1} ' +
                  'WHERE ExternalKey__c IN : keys AND IsApproved__c = true ';
        if(moduleExcludeIds != null){
            query += ' AND Id NOT in : moduleExcludeIds ';
        }
                  
        query += 'ORDER BY {2}';
        system.debug('query: ' + query);

    List<ModuleResponse__c> listModuleResponse;

     if(Schema.sObjectType.ModuleResponse__c.isAccessible()){	

        listModuleResponse = (List<ModuleResponse__c>) Database.query(String.format(query,
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

                    }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listModuleResponse;
    }

    public List<ModuleResponse__c> selectModuleResponseIds(Set<Id> coursesIds) {
                String query = 'SELECT {0} ' +
                    'FROM {1} ' +
                    'WHERE Module__r.Course__c IN :  coursesIds';

     List<ModuleResponse__c> listModuleResponse;

     if(Schema.sObjectType.ModuleResponse__c.isAccessible()){	

        listModuleResponse = (List<ModuleResponse__c>) Database.query(String.format(query,
                new List<String> {
                    getFieldListString(),
                    getSObjectName() } ));

        }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listModuleResponse;
    }

    public List<ModuleResponse__c> selectByIdHavingCourseStatus(Set<Id> recordIds) {

    List<ModuleResponse__c> listModuleResponse;

     if(Schema.sObjectType.ModuleResponse__c.isAccessible()){	

        listModuleResponse = (List<ModuleResponse__c>) Database.query(String.format(
                'SELECT {0} ' +               
                  'FROM {1} ' +
                  'WHERE CourseStatus__c IN :recordIds' ,
                 
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));

                    }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listModuleResponse;
    }
    
    public List<ModuleResponse__c> selectByIdWithQuestionPool(Set<Id> moduleResponseIds) {
    
    List<ModuleResponse__c> listModuleResponse;

     if(Schema.sObjectType.ModuleResponse__c.isAccessible()){	

        listModuleResponse = (List<ModuleResponse__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', Module__r.QuestionPool__c ' +
                  'FROM {1} ' +
                  'WHERE Id IN :moduleResponseIds AND Module__r.QuestionPool__c != null' ,
                 
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));
            }else{
                throw new FieloException(Label.CannotAccessRecords);
            }

             return listModuleResponse;
    }   
        
    public List<AggregateResult> selectByKeyGroupByKey(Set<String> keys) {

         List<AggregateResult> listQuestion;

       if(Schema.sObjectType.ModuleResponse__c.isAccessible()){	

        listQuestion = [SELECT MAX(NumberOfAttempt__c) attemptNumber, ExternalKey__c FROM ModuleResponse__c WHERE ExternalKey__c in : keys GROUP BY ExternalKey__c];

         }else{
            throw new FieloException(Label.CannotAccessRecords);
          }

          return listQuestion;
    }
}