src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>SubscriptionMode__c</fullName>
        <inlineHelpText>Choose &quot;Manual&quot; to require members to join a course before participating, or &quot;Automatic&quot; to allow members to jump right into taking modules.</inlineHelpText>
        <label>Subscription Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Automatic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseStatus__c.object
<CustomObject>
    <fields>
        <fullName>ApprovedModules__c</fullName>
        <label>Approved Modules</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses Status</relationshipLabel>
        <relationshipName>CoursesStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Progress__c</fullName>
        <formula>ApprovedModules__c / Course__r.ActiveModules__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Progress</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Course Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Course Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__PublicSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Application configuration.</description>
    <label>Public Settings</label>
</CustomObject>

src/objects/Module__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Course to which the module belongs.</description>
        <inlineHelpText>Course to which the module belongs.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Modules</relationshipLabel>
        <relationshipName>Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ModuleResponse__c.object
<CustomObject>
    <fields>
        <fullName>CourseStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Status</label>
        <referenceTo>CourseStatus__c</referenceTo>
        <relationshipLabel>Modules Responses</relationshipLabel>
        <relationshipName>ModuleResponses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSubmitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Module Responses</relationshipLabel>
        <relationshipName>ModuleResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Module Response</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Module Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUpdateApprovedModulesBatchSchedule.cls
@isTest
public class TestUpdateApprovedModulesBatchSchedule {

    @testSetup static void setup(){
        MockUpFactory.InsertTestData();
        System.debug('Number of Queries used in this apex code so far: ' + Limits.getQueries());
        System.debug('Number of rows queried in this apex code so far: ' + Limits.getDmlRows());
    }
    
    @isTest
    static void runUpdate(){
        Test.startTest();
        Course__c course = [SELECT Id FROM Course__c WHERE Name = 'Course 0' LIMIT 1];
        
        course.SubscriptionMode__c = 'Automatic';
        
        update course;

        System.assertEquals('Automatic', [SELECT SubscriptionMode__c FROM Course__c WHERE Id = :course.Id LIMIT 1].SubscriptionMode__c);

        MockUpFactory.activateCourse();

        System.debug('Number of Queries used in this apex code so far: ' + Limits.getQueries());
        System.debug('Number of rows queried in this apex code so far: ' + Limits.getDmlRows());

        FieloPLT__Member__c member = [SELECT Id, FieloPLT__Program__c FROM FieloPLT__Member__c WHERE Name = 'Member 0' LIMIT 1];
        List<Module__c> modules = [SELECT Id, Course__c FROM Module__c WHERE Name IN ('Basic','Intermediate') AND Course__c = :course.Id ORDER BY Name];
        FieloELR__Module__c module1 = modules[0];
        FieloELR__Module__c module2 = modules[1];

        ModuleService.ModuleWrapper moduleWrapper1 = FieloELR.ModuleService.takeModule(
            module1.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );
        
        System.debug('Number of Queries used in this apex code so far: ' + Limits.getQueries());
        System.debug('Number of rows queried in this apex code so far: ' + Limits.getDmlRows());
        
        System.assertEquals(String.valueOf(course.Id) + String.valueOf(member.Id), [SELECT ExternalKey__c FROM CourseStatus__c LIMIT 1].ExternalKey__c);
        
        MockUpFactory.answerModuleCorrectly(moduleWrapper1);

        System.debug('Number of Queries used in this apex code so far: ' + Limits.getQueries());
        System.debug('Number of rows queried in this apex code so far: ' + Limits.getDmlRows());
        
        System.assertEquals(1, [SELECT count() FROM CourseStatus__c]);
        
        ModuleResponse__c mr = [SELECT Id, IsSubmitted__c, IsApproved__c FROM ModuleResponse__c WHERE Id = :moduleWrapper1.moduleResponse.Id];
        
        System.assertEquals(true, mr.isSubmitted__c);
        System.assertEquals(true, mr.IsApproved__c);
        
        ModuleService.ModuleWrapper moduleWrapper2 = FieloELR.ModuleService.takeModule(
            module2.Id,
            member.Id,
            new Set<String> {'Id', 'FieloELR__AttemptsAllowed__c'},
            new Set<String> {'FieloELR__QuestionText__c'},
            new Set<String> {'FieloELR__AnswerOptionText__c','FieloELR__MatchingText__c','FieloELR__IsCorrect__c'}
        );
        
        MockUpFactory.answerModuleCorrectly(moduleWrapper2);
        
        mr = [SELECT Id, IsSubmitted__c, IsApproved__c, CourseStatus__c, CourseStatus__r.Progress__c, CourseStatus__r.Course__r.Name, CourseStatus__r.ApprovedModules__c FROM ModuleResponse__c WHERE Id = :moduleWrapper2.moduleResponse.Id];
        
        System.assertEquals(true, mr.isSubmitted__c);
        System.assertEquals(true, mr.IsApproved__c);
        System.assertEquals(1, [SELECT Count() FROM CourseStatus__c]);
        System.assertEquals('Course 0',mr.CourseStatus__r.Course__r.Name);
        System.assertEquals(2,mr.CourseStatus__r.ApprovedModules__c);
        System.assertEquals(100, mr.CourseStatus__r.FieloELR__Progress__c);
        
        insert new FieloPLT__PublicSettings__c (FieloELR__EnableEditingWhileActive__c  = true);
        
        update new Module__c(
            Id = module1.Id,
            IsActive__c = false
        );
        
        DataBase.executeBatch(new UpdateApprovedModulesBatchSchedule());
        Test.stopTest();
        
    }
}