src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>ActiveModules__c</fullName>
        <label>Active Modules</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubscriptionMode__c</fullName>
        <inlineHelpText>Choose &quot;Manual&quot; to require members to join a course before participating, or &quot;Automatic&quot; to allow members to jump right into taking modules.</inlineHelpText>
        <label>Subscription Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Automatic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseStatus__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses Status</relationshipLabel>
        <relationshipName>CoursesStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Course Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Tracker__c.object
<CustomObject>
    <description>Internal object. It is generated as a result of processing a Challenge Action.</description>
    <fields>
        <fullName>CourseStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Status</label>
        <referenceTo>CourseStatus__c</referenceTo>
        <relationshipLabel>Trackers</relationshipLabel>
        <relationshipName>Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, Tracker is processed. Depending on the other Challenge settings and status, several related processes may be triggered.</description>
        <inlineHelpText>If ticked, Tracker is processed.</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsReverted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, Tracker is reverted thus Points are returned to the Member.</description>
        <inlineHelpText>If ticked, Tracker is reverted thus Points are returned to the Member.</inlineHelpText>
        <label>Reverted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Member who performed the Action generating the Tracker.</description>
        <inlineHelpText>Member who performed the Action generating the Tracker.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Trackers</relationshipLabel>
        <relationshipName>Trackers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>FieloPLT__Transaction__c</referenceTo>
        <relationshipLabel>Trackers</relationshipLabel>
        <relationshipName>Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tracker</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Transaction__c.object
<CustomObject>
    <description>Actions that grant Points, Badges or Rewards to Members in exchange of performing specific activities.</description>
    <fields>
        <fullName>CourseStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Status</label>
        <referenceTo>CourseStatus__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, Transactions were processed by the Rule Engine.</description>
        <inlineHelpText>When ticked, Transactions were processed.</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsReverted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, Transactions were reverted by the Rule Engine.</description>
        <inlineHelpText>When ticked, Transactions were reverted.</inlineHelpText>
        <label>Reverted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It shows the Member who generated the Transaction.</description>
        <inlineHelpText>Enter the Member who generated the Transaction.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Points__c</fullName>
        <description>Transaction Points.</description>
        <inlineHelpText>Enter the number of Transaction Points.</inlineHelpText>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__RevertedTransaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It shows a Transaction that was reverted.</description>
        <inlineHelpText>Transaction that was reverted.</inlineHelpText>
        <label>Reverted Transaction</label>
        <referenceTo>FieloPLT__Transaction__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CourseDetailsController.cls
public with sharing class CourseDetailsController {
		
		@AuraEnabled
		public static FieloELR__Course__c getCourse(ID courseId){
			try{
				List <FieloELR__Course__c> courses = (List <FieloELR__Course__c>)[SELECT Name, Description__c, StartDate__c, EndDate__c, Image__c, ActiveModules__c, Status__c, SubscriptionMode__c FROM Course__c WHERE Id =: courseId LIMIT 1];
				if (courses.size() > 0) {
					System.debug(courses[0]);
					return courses[0];
				}
			} 
			catch (DmlException e) {
				throw new AuraHandledException(e.getDmlMessage(0));
			} 
			catch (Exception e) {
				throw new AuraHandledException(e.getMessage());
			}
			return null;
		}

		@AuraEnabled
		public static String getConfig(String recordId, String memberId, String csFields){
			try {
				Map<String,String> lcConfig = new Map<String,String>();
				String baseUrl = Network.getLoginUrl(Network.getNetworkId());
				System.debug(baseUrl);
				String uselessString = baseURL.substring(baseURL.lastIndexOf('/')+1);
				System.debug(uselessString);
				baseURL = baseURL.replace(uselessString, '').replace('/s/','/');
				System.debug(baseUrl);
				System.debug(JSON.serialize(csFields));
				Set<String> queryableFields = new Set<String>();
				Set<String> fieldNames = new Set<String>();
				if (csFields != null) {
					fieldNames.addAll(csFields.split(','));
					for(String fieldName:fieldNames) {
						if (fieldName == 'FieloELR__Transactions__r') {
							queryableFields.add('(SELECT Id, FieloPLT__Points__c FROM FieloELR__Transactions__r WHERE FieloPLT__IsReverted__c = false AND FieloPLT__IsProcessed__c = true) FieloELR__Transactions__r');
						} else if (fieldName == 'FieloELR__Trackers__r') {
							queryableFields.add('(SELECT Id, FieloPLT__Transaction__r.FieloPLT__Points__c FROM FieloELR__Trackers__r WHERE FieloPLT__IsReverted__c = false AND FieloPLT__IsProcessed__c = true) FieloELR__Trackers__r');
						} else {
							queryableFields.add(fieldName);
						}
					}
				}
				List<CourseStatus__c> csList = new List<CourseStatus__c>(new CourseStatusSelector(queryableFields).selectByKey(new Set<String>{String.valueOf(recordId) + String.valueOf(memberId)}));
				System.debug(JSON.serialize(csList));

				lcConfig.put('orgId', UserInfo.getOrganizationId());
				lcConfig.put('locale', UserInfo.getLocale());
				lcConfig.put('profileId', UserInfo.getProfileId());
				lcConfig.put('communityURL', baseURL);
				lcConfig.put('joinedCourse', String.valueOf(!csList.isEmpty()));
				lcConfig.put('orgId', UserInfo.getOrganizationId());
				
				System.debug(JSON.serialize(lcConfig));
				return JSON.serialize(lcConfig);
				
			}
			catch(DMLException e){
				throw new AuraHandledException(e.getDMLMessage(0));	
			} 
			catch (Exception e) {
				throw new AuraHandledException(e.getMessage());
			}


		}

		@AuraEnabled
		public static String getCourseStatus(FieloPLT__Member__c member, Id courseId, Boolean includePoints) {
		try{
			Id memberId = member.Id;
			String key = String.valueOf(courseId) + String.valueOf(memberId);

			Set<String> fieldsModuleResponse = new Set<String>();
			fieldsModuleResponse.add('Id');
			fieldsModuleResponse.add('FieloELR__Module__c');
			fieldsModuleResponse.add('FieloELR__IsApproved__c');
			fieldsModuleResponse.add('FieloELR__NumberOfAttempt__c');
			fieldsModuleResponse.add('FieloELR__NumberofApprove__c');
			fieldsModuleResponse.add('FieloELR__GradePercent__c');
			fieldsModuleResponse.add('FieloELR__SubmitDate__c');
			fieldsModuleResponse.add('FieloELR__CorrectQuestions__c');
			fieldsModuleResponse.add('FieloELR__IncorrectQuestions__c');
			fieldsModuleResponse.add('FieloELR__CourseStatus__r.FieloELR__Progress__c');
			fieldsModuleResponse.add('FieloELR__CourseStatus__r.FieloELR__Course_Accomplished__c');

			if (includePoints != null && includePoints) {
				fieldsModuleResponse.add('(SELECT Id, FieloPLT__Points__c FROM FieloELR__Transactions__r WHERE FieloPLT__IsReverted__c = false AND FieloPLT__IsProcessed__c = true) FieloELR__Transactions__r');
                fieldsModuleResponse.add('(SELECT Id, FieloPLT__Transaction__r.FieloPLT__Points__c FROM FieloELR__Trackers__r WHERE FieloPLT__IsReverted__c = false AND FieloPLT__IsProcessed__c = true) FieloELR__Trackers__r');
			}
			
			String queryModuleResponse = 'SELECT ' + String.join(new List<String>(fieldsModuleResponse), ',');
			queryModuleResponse += ' FROM FieloELR__ModuleResponse__c WHERE FieloELR__CourseStatus__r.FieloELR__ExternalKey__c = :key';

			System.debug(JSON.serialize(Database.query(queryModuleResponse)));

			return JSON.serialize(Database.query(queryModuleResponse));
		} catch(DMLException e) {
           	throw new AuraHandledException(e.getDMLMessage(0));
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
	}
}