src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubscriptionMode__c</fullName>
        <inlineHelpText>Choose &quot;Manual&quot; to require members to join a course before participating, or &quot;Automatic&quot; to allow members to jump right into taking modules.</inlineHelpText>
        <label>Subscription Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Automatic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseStatus__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses Status</relationshipLabel>
        <relationshipName>CoursesStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Courses Status</relationshipLabel>
        <relationshipName>CoursesStatus</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Course Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Course Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Module__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalGrade__c</fullName>
        <label>Approval Grade</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>AttemptsAllowedPerQuestion__c</fullName>
        <label>Attempts Allowed per Question</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AttemptsAllowed__c</fullName>
        <label>Attempts Allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Course to which the module belongs.</description>
        <inlineHelpText>Course to which the module belongs.</inlineHelpText>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Modules</relationshipLabel>
        <relationshipName>Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PenaltyMode__c</fullName>
        <label>Penalty Mode</label>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Percent Decrease</fullName>
                </value>
                <value>
                    <fullName>Negative Weight</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ShuffleQuestions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Shuffle Questions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WeightedQuestions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Weighted Questions</label>
        <type>Checkbox</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCourseStatusViewController.cls
@isTest
public class TestCourseStatusViewController {
	@testSetup static void setup(){
        MockUpFactory.InsertTestData();
    }	

	@isTest static void getTests(){
 		
 		List<FieloPLT__Program__c> programs = [SELECT Id FROM FieloPLT__Program__c];

 		FieloPLT__Segment__c metaSegment =
			MockUpFactory.createSegments('Segment #', 1, 'MetaSegment')[0];
		List<FieloPLT__Segment__c> segments =
			MockUpFactory.createSegments('Segment #', 2, 'Manual');

		

		for (FieloPLT__Segment__c segment:segments) {
			segment.FieloPLT__Program__c = programs[0].Id;
		}

		insert segments;

		metaSegment.FieloPLT__RelatedSegments__c = segments[0].Id + ';' + segments[1].Id;
		metaSegment.FieloPLT__Program__c = programs[0].Id;

		insert metaSegment;

		//Course
 		FieloELR__Course__c course = new FieloELR__Course__c(
 			Name = 'Dev Course'
 			, SubscriptionMode__c = 'Manual'
 			, Program__c = programs[0].Id);

 		insert course;

 		FieloELR__Module__c module = new FieloELR__Module__c(
			Name = 'Developers Module'
			, Course__c = course.Id
			, ApprovalGrade__c = 80.0
			, AttemptsAllowed__c = 10
			, AttemptsAllowedPerQuestion__c = 10
			, Description__c = 'Developers Course Description'
			, Order__c = 1
			, PenaltyMode__c = 'None'
			, ShuffleQuestions__c = true
			, WeightedQuestions__c = true
		);

		insert module;

		//TODO QUery um program e botar dentro do course
		List<FieloELR__Module__c> modules = [SELECT Id, IsActive__c FROM Module__c];
		modules.get(0).IsActive__c = true;
		upsert modules.get(0);

		System.assertEquals(true, modules.get(0).IsActive__c);

		List<FieloELR__Course__c> courses = new List<FieloELR__Course__c>();
		courses = [SELECT Id, Status__c FROM Course__c WHERE Program__c =: programs.get(0).id];
		courses.get(0).Status__c = 'Active';
		update courses;
		
		System.assertEquals('Active', courses.get(0).Status__c);

 		//Members
 		List<FieloPLT__Member__c> members = new List<FieloPLT__Member__c>();
 		members = [SELECT Id FROM FieloPLT__Member__c WHERE FieloPLT__Program__c =: programs.get(0).id];
        update members;


        //CourseStatus
	   	FieloELR__CourseStatus__c record = new FieloELR__CourseStatus__c(
		Member__c = members.get(0).id
		,Course__c = courses.get(0).id);
		insert record;
	
	   	  //ModuleResponse
        FieloELR__ModuleResponse__c moduleRes = new FieloELR__ModuleResponse__c(
        	Member__c = members.get(0).id
        	,Module__c = modules.get(0).id
        	,CourseStatus__c = record.Id);

        upsert moduleRes;

	   	//StandardController
	   	ApexPages.StandardController standardController = new ApexPages.StandardController(record);

    	CourseStatusViewController crsStViewController = new CourseStatusViewController(standardController);

    	RemoteActionResult resultSave = CourseStatusViewController.save(
			record,
			new List<String>{
				'FieloELR__StartDate__c',
				'FieloELR__EndDate__c'
			}
		);

		RemoteActionResult resutSaveModuleRes = CourseStatusViewController.saveModuleResponse(
			moduleRes,
			new List<String>{
				'FieloELR__StartDate__c'}
		);
    	
		String fields = String.join( new List<String>(Schema.describeSObjects(
			new String[]{'FieloELR__Course__c'})[0].fields.getMap().keySet()) ,',');

		FieloELR__Course__c retrievedCourse = (FieloELR__Course__c) CourseStatusViewController.retrieve('FieloELR__Course__c', course.Id, fields);

	}

	
	@isTest
	static void testSectionFormField() {
	
	CourseStatusViewController.Section section = new CourseStatusViewController.Section();
	section.Name =  'none';
	section.CssClass = 'none';

	System.assertEquals('none', section.Name);
	System.assertEquals('none', section.CssClass);


	CourseStatusViewController.FormField formfield = new CourseStatusViewController.FormField();
	formfield.Type = 'none';
	formfield.MetaField = 'none';
	formfield.onchange = 'none';
	formfield.Label = 'none';
	formfield.Value = 'none';
  	formfield.Name = 'none';
    formfield.WhereCondition = 'none';
    
    List<CourseStatusViewController.FormField> innerList = new List<CourseStatusViewController.FormField>{formfield};
   section.Rows = new List<List<CourseStatusViewController.FormField>>{innerList};


    System.assertEquals('none', formfield.Type);
    System.assertEquals('none', formfield.MetaField);
    System.assertEquals('none', formfield.onchange);
    System.assertEquals('none', formfield.Value);
    System.assertEquals(null, formfield.Required);
    System.assertEquals('', formfield.getRequiredValue());
    
    formfield.Required = true;
    System.assertEquals(true, formfield.Required);
    System.assertEquals('true', formfield.getRequiredValue());

	}
}