src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseStatus__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses Status</relationshipLabel>
        <relationshipName>CoursesStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Courses Status</relationshipLabel>
        <relationshipName>CoursesStatus</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Course Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Course Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseAction.cls
public with sharing class CourseAction {
	@AuraEnabled
	public static String joinCourse(String memberId, String courseId) {
		try{
            if (true) {
				SObjectUnitOfWork uow = new SObjectUnitOfWork(new List<Schema.SObjectType>{CourseStatus__c.SObjectType});
				CourseStatus__c cs = new CourseStatus__c(
					Course__c = courseId,
					Member__c = memberId
				);
				uow.registerNew(cs);
				
				if ( Schema.sObjectType.CourseStatus__c.isCreateable() && Schema.sObjectType.CourseStatus__c.isUpdateable()) {
					if (Schema.sObjectType.CourseStatus__c.fields.Course__c.isCreateable() && Schema.sObjectType.CourseStatus__c.fields.Course__c.isUpdateable() && Schema.sObjectType.CourseStatus__c.fields.Member__c.isCreateable() && Schema.sObjectType.CourseStatus__c.fields.Member__c.isUpdateable()) {
						uow.commitWork();
					} else {
						throw new FieloException(String.format(Label.security_error_field_not_insertable, new List<String>{'CourseStatus__c', 'Course__c,Member__c'}));
					}
				} else {
					throw new FieloException(String.format(Label.security_error_object_not_readable, new List<String>{'CourseStatus__c'}));
				}

				return courseId;
			}
        } catch (DmlException e) {
            throw new AuraHandledException(e.getDmlMessage(0));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return null;
	}
}