src/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>FieloPLT__Program__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To target your course by segment, add the segment(s) you want to make eligible. If blank, all program members will be eligible. You can view, edit and create segments in the Programs tab.</inlineHelpText>
        <label>Segment</label>
        <referenceTo>FieloPLT__Segment__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubscriptionMode__c</fullName>
        <inlineHelpText>Choose &quot;Manual&quot; to require members to join a course before participating, or &quot;Automatic&quot; to allow members to jump right into taking modules.</inlineHelpText>
        <label>Subscription Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Automatic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseDependency__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Predecessor Courses</relationshipLabel>
        <relationshipName>PredecessorCourses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Predecessor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Predecessor</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Dependent Courses</relationshipLabel>
        <relationshipName>DependentCourses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Course Dependency</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Course Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseStatus__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Courses Status</relationshipLabel>
        <relationshipName>CoursesStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Course Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CoursesSelector.cls
public with sharing class CoursesSelector extends SObjectSelector{
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                Course__c.Id,
                Course__c.Name,
                Course__c.Description__c,
                Course__c.EndDate__c,
                Course__c.Program__c,
                Course__c.Segment__c,
                Course__c.StartDate__c,
                Course__c.Status__c,
                Course__c.SubscriptionMode__c    
            };
    }

    public CoursesSelector(Set<String> fields){
        super(fields);
    }

    public CoursesSelector(){
        super();
    }

    public Schema.SObjectType getSObjectType(){
        return Course__c.sObjectType;
    }

    public List<Course__c> selectById(Set<Id> CourseIds){
        return (List<Course__c>) selectSObjectsById(CourseIds);
    }

    public List<Course__c> selectByIdHavingCourseStatus(Set<Id> courseIds) {
      return (List<Course__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', (SELECT Id ' +
                  '   FROM CoursesStatus__r LIMIT 1) ' +
                  'FROM {1} ' +
                  'WHERE Id IN :courseIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));
    }
    
      public List<Course__c> selectAllByIdHavingCourseStatus(Set<Id> courseIds) {
      return (List<Course__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', (SELECT Id ' +
                  '   FROM CoursesStatus__r) ' +
                  'FROM {1} ' +
                  'WHERE Id IN :courseIds',
                new List<String> {
                    getFieldListString(),
                    getSObjectName() } ));
    }

    public List<Course__c> selectByIdHavingDependentCourses(Set<Id> courseIds) {
      return (List<Course__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', (SELECT Id ' +
                  '   FROM DependentCourses__r LIMIT 1) ' +
                  'FROM {1} ' +
                  'WHERE Id IN :courseIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));
    }
    public List<Course__c> selectByIdHavingPredecessorCourses(Set<Id> courseIds) {
      return (List<Course__c>) Database.query(String.format(
                'SELECT {0} ' +
                  ', (SELECT Id ' +
                  '   FROM PredecessorCourses__r LIMIT 1) ' +
                  'FROM {1} ' +
                  'WHERE Id IN :courseIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));
    }

    public List<Course__c> selectByIdHavingPredecessor(Set<Id> courseIds, Set<String> courseDependencyFields) {
      return (List<Course__c>) Database.query(String.format('SELECT {0} ' +
                   ', (SELECT {1} FROM PredecessorCourses__r) ' +
                  'FROM {2} ' +
                  'WHERE Id IN :courseIds ' +
                  'ORDER BY {3}',
                new List<String> {
                    getFieldListString(),
                    String.join(new List<String>(courseDependencyFields),','),
                    getSObjectName(),
                    getOrderBy() } ));
    }

    public List<Course__c> selectByProgramHavingPredecessor(Id programId, Set<String> courseDependencyFields) {
      return (List<Course__c>) Database.query(String.format('SELECT {0} ' +
                   ', (SELECT {1} FROM PredecessorCourses__r) ' +
                  'FROM {2} ' +
                  'WHERE Program__c =: programId ' +
                  'ORDER BY {3}',
                new List<String> {
                    getFieldListString(),
                    String.join(new List<String>(courseDependencyFields),','),
                    getSObjectName(),
                    getOrderBy() } ));
    }

    public List<Course__c> selectByIdHavingPredecessor(Set<Id> courseIds) {
      return (List<Course__c>) Database.query(String.format(
               'SELECT {0} ' +
                   ', (SELECT Course__c, Predecessor__c ' +
                  '   FROM PredecessorCourses__r) ' +
                  'FROM {1} ' +
                  'WHERE Id IN :courseIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));
    }

      public List<Course__c> selectByIdBeingAutomatic(Set<Id> courseIds) {
      String automatic = 'Automatic';
      return (List<Course__c>) Database.query(String.format(       
               'SELECT {0} ' +                
                  'FROM {1} ' +
                  'WHERE Id IN : courseIds and SubscriptionMode__c = :automatic ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));
    }
}