src/objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CourseDependency__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Predecessor Courses</relationshipLabel>
        <relationshipName>PredecessorCourses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Predecessor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Predecessor</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Dependent Courses</relationshipLabel>
        <relationshipName>DependentCourses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Course Dependency</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Course Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseDependenciesSelector.cls
public with sharing class CourseDependenciesSelector extends SObjectSelector{
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                CourseDependency__c.Id,
                CourseDependency__c.Name,
                CourseDependency__c.Course__c,
                CourseDependency__c.Predecessor__c                  
            };
    }

    public CourseDependenciesSelector(Set<String> fields){
        super(fields);
    }

    public CourseDependenciesSelector(){
        super();
    }

    public Schema.SObjectType getSObjectType(){
        return CourseDependency__c.sObjectType;
    }

    public List<CourseDependency__c> selectById(Set<Id> CourseDependenciesIds){
        return (List<CourseDependency__c>) selectSObjectsById(CourseDependenciesIds);
    }

    public List<CourseDependency__c> selectDependenciesAndPredecessors(Set<Id> recordIds) {
      return (List<CourseDependency__c>) Database.query(String.format(
                'SELECT {0} ' +               
                  'FROM {1} ' +
                  'WHERE Course__c IN :recordIds OR Predecessor__c IN :recordIds' ,
                 
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));
    }


}