src/objects/FieloPLT__Tracker__c.object
<CustomObject>
    <description>Internal object. It is generated as a result of processing a Challenge Action.</description>
    <fields>
        <fullName>FieloPLT__IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, Tracker is processed. Depending on the other Challenge settings and status, several related processes may be triggered.</description>
        <inlineHelpText>If ticked, Tracker is processed.</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsReverted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If ticked, Tracker is reverted thus Points are returned to the Member.</description>
        <inlineHelpText>If ticked, Tracker is reverted thus Points are returned to the Member.</inlineHelpText>
        <label>Reverted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Member who performed the Action generating the Tracker.</description>
        <inlineHelpText>Member who performed the Action generating the Tracker.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Trackers</relationshipLabel>
        <relationshipName>Trackers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>FieloPLT__Transaction__c</referenceTo>
        <relationshipLabel>Trackers</relationshipLabel>
        <relationshipName>Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ModuleResponse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module Response</label>
        <referenceTo>ModuleResponse__c</referenceTo>
        <relationshipLabel>Trackers</relationshipLabel>
        <relationshipName>Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tracker</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Transaction__c.object
<CustomObject>
    <description>Actions that grant Points, Badges or Rewards to Members in exchange of performing specific activities.</description>
    <fields>
        <fullName>FieloPLT__IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, Transactions were processed by the Rule Engine.</description>
        <inlineHelpText>When ticked, Transactions were processed.</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsReverted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When ticked, Transactions were reverted by the Rule Engine.</description>
        <inlineHelpText>When ticked, Transactions were reverted.</inlineHelpText>
        <label>Reverted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It shows the Member who generated the Transaction.</description>
        <inlineHelpText>Enter the Member who generated the Transaction.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Points__c</fullName>
        <description>Transaction Points.</description>
        <inlineHelpText>Enter the number of Transaction Points.</inlineHelpText>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__RevertedTransaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It shows a Transaction that was reverted.</description>
        <inlineHelpText>Transaction that was reverted.</inlineHelpText>
        <label>Reverted Transaction</label>
        <referenceTo>FieloPLT__Transaction__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ModuleResponse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module Response</label>
        <referenceTo>ModuleResponse__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Module__c.object
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ModuleResponse__c.object
<CustomObject>
    <fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Module Responses</relationshipLabel>
        <relationshipName>ModuleResponses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Module Response</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Module Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CourseModulesController.cls
public with sharing class CourseModulesController {
	@AuraEnabled
	public static String getCourseMap(FieloPLT__Member__c member, Id courseId, String modulesFieldset, Boolean includePoints, Boolean includeQuestions) {
		try{
			Id memberId = member.Id;
			Id programId = member.FieloPLT__Program__c;
			Set<String> fieldsModule = new Set<String> ( modulesFieldset.split(',') );

			if (includeQuestions) {
				fieldsModule.add('FieloELR__NumberOfQuestions__c');
			}

			Set<String> fieldsModuleResponse = new Set<String>();
			fieldsModuleResponse.add('Id');
			fieldsModuleResponse.add('FieloELR__Module__c');

			if (includePoints != null && includePoints) {
				fieldsModuleResponse.add('(SELECT Id, FieloPLT__Points__c FROM FieloELR__Transactions__r WHERE FieloPLT__IsReverted__c = false AND FieloPLT__IsProcessed__c = true) FieloELR__Transactions__r');
                fieldsModuleResponse.add('(SELECT Id, FieloPLT__Transaction__r.FieloPLT__Points__c FROM FieloELR__Trackers__r WHERE FieloPLT__IsReverted__c = false AND FieloPLT__IsProcessed__c = true) FieloELR__Trackers__r');
			}

			List<CourseService.CourseWrapper> coursesMap;
			
			coursesMap = CourseService.getCoursesMap(
				new Set<String>{'Id','FieloELR__SubscriptionMode__c','FieloELR__Status__c'},
				new Set<String>{'Id','Name'},
				fieldsModule,
				null,
				new Set<Id>{courseId},
				programId,
				memberId,
				false,
				true,
				100,
				0,
				'FieloELR__Order__c',
				''
			);

			List<CourseService.ModuleWrapper> mws = new List<CourseService.ModuleWrapper>();
			
			Set<Id> mrIds = new Set<Id>();

			for( CourseService.ModuleWrapper mw:coursesMap[0].modules) {
				if (mw.moduleResponses != null) {
					if (!mw.moduleResponses.isEmpty()) {
						mrIds.addAll(new Map<Id,ModuleResponse__c>(mw.moduleResponses).keySet());
					}
				}
			}

			if (!mrIds.isEmpty()) {
				Map<Id,ModuleResponse__c> mrMap = new Map<Id,ModuleResponse__c>(new ModuleResponsesSelector(fieldsModuleResponse).selectById(mrIds));
				Map<Id,List<ModuleResponse__c>> mrMapByModule = new Map<Id,List<ModuleResponse__c>>();
				for( ModuleResponse__c mr: mrMap.values()) {
					if (!mrMapByModule.containsKey(mr.Module__c)) {
						mrMapByModule.put(mr.Module__c, new List<ModuleResponse__c>());
					}
					mrMapByModule.get(mr.Module__c).add(mr);
				}

				for( CourseService.ModuleWrapper mw:coursesMap[0].modules) {
					if (!mw.moduleResponses.isEmpty()) {
						mws.add(new CourseService.ModuleWrapper(mw.module, mrMapByModule.get(mw.module.Id)));
					}
				}

				coursesMap[0].modules.clear();
				coursesMap[0].modules.addAll(mws);
			}

			return JSON.serialize(coursesMap);
		} catch(DMLException e) {
           	throw new AuraHandledException(e.getDMLMessage(0));
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
	}

	@AuraEnabled
	public static String getCourseMap(FieloPLT__Member__c member, Id courseId, String modulesFieldset, Boolean includePoints, Boolean includeQuestions) {
		try{

			return JSON.serialize(coursesMap);
		} catch(DMLException e) {
           	throw new AuraHandledException(e.getDMLMessage(0));
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
	}
}