src/objects/Module__c.object
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ModuleDependency__c.object
<CustomObject>
    <fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Predecessor Modules</relationshipLabel>
        <relationshipName>PredecessorModules</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Predecessor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Predecessor</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Dependent Modules</relationshipLabel>
        <relationshipName>DependentModules</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Module Dependency</label>
    <nameField>
        <displayFormat>MD-{00000000}</displayFormat>
        <label>Module Dependency Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules Dependencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ModuleDependenciesSelector.cls
public class ModuleDependenciesSelector extends SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                ModuleDependency__c.Id,
                ModuleDependency__c.Name,
                ModuleDependency__c.Module__c,
                ModuleDependency__c.Predecessor__c,
                ModuleDependency__c.ExternalKey__c
            };
    }

    public ModuleDependenciesSelector(Set<String> fields){
        super(fields);
    }

    public ModuleDependenciesSelector(){
        super();
    }

    public Schema.SObjectType getSObjectType(){
        return ModuleDependency__c.sObjectType;
    }

    public List<ModuleDependency__c> selectById(Set<Id> moduleDependencyIds){
        return (List<ModuleDependency__c>) selectSObjectsById(moduleDependencyIds);
    }

    public List<ModuleDependency__c> selectByModule(Set<Id> moduleIds) {
        return (List<ModuleDependency__c>) Database.query(String.format(
                'SELECT {0} ' +
                  'FROM {1} ' +
                  'WHERE (Module__c IN :moduleIds OR Predecessor__c IN :moduleIds) ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));
    }

    public List<ModuleDependency__c> selectByPredecessor(Set<Id> moduleIds) {
        return (List<ModuleDependency__c>) Database.query(String.format(
                'SELECT {0} ' +
                  'FROM {1} ' +
                  'WHERE Predecessor__c IN :moduleIds ' +
                  'ORDER BY {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));
    }
}