src/objects/Module__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUpdateActiveModulesBatchSchedule.cls
@isTest
public class TestUpdateActiveModulesBatchSchedule {

    @testSetup static void setup(){
        MockUpFactory.InsertTestData();
    }
    
    @isTest
    static void runUpdate(){
        List<Module__c> modules = [SELECT Id FROM Module__c WHERE IsActive__c != true];

        for (Module__c module: modules) {
            module.IsActive__c = true;
        }

        update modules;
        
        Test.startTest();
        DataBase.executeBatch(new UpdateActiveModulesBatchSchedule());
        Test.stopTest();
        
    }
}